<Project Sdk="Microsoft.NET.Sdk">

	<PropertyGroup>
		<RootNamespace>OceanApocalypse.Wave.IDE.Samples.MinimalWorkingSample</RootNamespace>
		<OutputType>Exe</OutputType>
		<TargetFramework>net10.0</TargetFramework>
		<Nullable>enable</Nullable>
		<PublishAot>true</PublishAot>
		<InvariantGlobalization>true</InvariantGlobalization>
	</PropertyGroup>

	<ItemGroup>
		<ProjectReference Include="..\..\src\sdk\waveIDE.SDK.Protocol\waveIDE.SDK.Protocol.csproj" />
		<ProjectReference Include="..\..\tests\sdk\waveIDE.IpcTestServerLauncher\waveIDE.IpcTestServerLauncher.csproj" />
	</ItemGroup>

</Project>
