# Shared manifest - for when a single plugin supports multiple SDKs, operating systems, etc

[plugin] # the main metadata - cannot be specific
id = "dev.bob.my-plugin" # the plugin's unique ID - mandatory
version = "3.0.1" # version oif the plugin - mandatory
display_name = "Bob's Awesome Plugin" # display name of the plugin
author = "Bob" # name of the author
license = "Apache-2.0" # the SPDX license expression of the plugin
url = "https://example.com/bob/plugin"						# string, optional but highly recommended (url)
language = "C#" # the programming language the plugin is written it - used only for metadata
# no entry point can be shared


[[urls]] # URLs - cannot be specific
type = "source" # types are source, docs, home, tracker and other
value = "https://invent.example.com/" # the actual URL itself

[[urls]]
type = "docs"
name = "Read The Docs"
value = "https://example.com/product-docs/"


[permissions] # defines permissions - cannot be specific
# scopes vary with the editor and so varies the syntax of their definitions
scopes = [
	"trust:read",
	"workspace:read",
	"workspace:write",
	"debug:write",
	# ...
]


# defines the compatibility contract - can be shared, but is overriden by every specific that has their own compat settings
[compatibility]
conflicts = [ "dev.joe.i-hate-bob" ] # plugins that lead to conflicts when installed side by side

# editors where the compatibility with the plugin is known to exist - tested
# it's the editor that enforces this policy
# all the SDK does is clean up and interpret 'a:b' syntax
compatibleEditors = [
	"waveIDE", # targetting all versions for an editor
	"waveIDE:*", # same as above
	"waveIDE:3", # specific major version
	"waveIDE:3-1", # major version ranges
	"waveIDE:3.0", # specific minor versions
	"waveIDE:3.0.1", # specific patch versions
	"waveIDE:2-", # every version until a given one (included),
	"waveIDE:3.0.1-/",
	"waveIDE:3.1-2.9.0", # minor and patch ranges
	"waveIDE:2026", # year (any version dating '26 is compatible)
	"waveIDE:latest" # latest version
]

# editors where the compatibility is known to not exist - tested; same syntax applies as above
incompatibleEditors = [ "waveIDE:beta" ]

# defaults to false (if set to true, any editor not in 'compatible' is automatically incompatible)
# if set to false, editors not in 'compatible' are considered compatible, but untested
# it's up to the editor to decide whether something untested should try to run or straight up be disabled
unspecified_are_incompatible = true


[[themes]] # all themes that any target adds must be defined but they don't have to point to a file yet
name = "Example Theme"
file = "path/to/theme" # optional, this means this theme is by default path/to/theme unless a given specific overrides it

[[themes]]
name = "Bob's Amazing Theme"
# no file means each specific has to override


[[locales]] # all locales that any target adds must be defined but they don't have to point to a file yet
iso_name = "pt"			# must match a ISO 639-1/639-3 name
name = "pt-PT"			# must match a .NET culture name
file = "path/to/file"	# optional, this means this locale is by default path/to/file unless a given specific overrides it

[[locales]]
iso_name = "sk"			# must match a ISO 639-1/639-3 name
name = "sk-SK"			# must match a .NET culture name
# no file means each specific has to override


[languages.rsml] # all languages that any target adds must be defined here - they're purely declaration blocks, so it doesn't make sense for them to be specific
name = "Red Sea Modern Language"
file_extensions = [ "rsea", "rsml", "decision" ]
mime_type = "application/rsml"

[languages.rsml.capabilities] # some editors read these and add the missing permissions in the scopes
lsp = true
formatter = true
debugger = true


# targets block must be here
# targets are ordered by specificity
# on a machine where waveIDE uses SDK v3 and the CPU architecture is arm64, Sdk3Arm64 will be chosen over Sdk3, even though the Sdk3 constraint is defined before
[[targets]]
api_version = "3.x.x"
path = "Sdk3"

[[targets]]
api_version = "3.x.x"
arch = "arm64"
path = "Sdk3Arm64"

[[targets]]
api_version = "2"
os = "linux"
arch = "x64"
path = "Sdk2LinuxX64"
