<!-- Attributes for solution-wise code analysis. -->
<Project>
    <PropertyGroup>
        <AnalysisLevel>latest-all</AnalysisLevel>
        <AnalysisMode>All</AnalysisMode>

        <!-- CA1034 leads to false positives when using C# 14 extension members -->
        <!-- CA1043 doesn't let us do this[Range] and this[CustomType] -->
        <!-- CA1078 leads to false positives when using C# 14 extension members. Also, CS3001 is
        better for this check. -->
        <NoWarn>$(NoWarn);CA1034;CA1043;CA1708</NoWarn>
    </PropertyGroup>
</Project>