<Project>
    <PropertyGroup>
        <Authors>OceanApocalypse</Authors>
        <Company>OceanApocalypse</Company>
        <Copyright>Copyright 2026 OceanApocalypse</Copyright>
        <PackageLicenseExpression>AGPL-3.0-or-later</PackageLicenseExpression>

        <Description>The actual FLOSS alternative to VSCode.</Description>

        <RepositoryUrl>https://github.com/OceanApocalypse/waveIDE/</RepositoryUrl>
        <PackageProjectUrl>https://oceanapocalypse.org/waveIDE/</PackageProjectUrl>

        <PackageTags>foss;ide;code-editor;extensible;extensible-code-editor;no-telemetry</PackageTags>
        <PackageReadmeFile>README.md</PackageReadmeFile>
        <PackageIcon>icon.png</PackageIcon>

        <RepositoryType>git</RepositoryType>
        <PackageRequireLicenseAcceptance>true</PackageRequireLicenseAcceptance>
        <NeutralLanguage>en</NeutralLanguage>

        <IsPackable>true</IsPackable>
    </PropertyGroup>
</Project>