<Project>
    <PropertyGroup>
        <Authors>OceanApocalypse</Authors>
        <Company>OceanApocalypse</Company>
        <Copyright>Copyright (C) 2026  Ocean Apocalypse</Copyright>
        <PackageLicenseExpression>Apache-2.0</PackageLicenseExpression>

        <Description>The only DSL that dynamically interprets different logic paths based on an
            host's OS and CPU architecture.</Description>

        <RepositoryUrl>https://github.com/OceanApocalypse/RedSeaModernLanguage/</RepositoryUrl>
        <PackageProjectUrl>https://oceanapocalypse.org/rsml-docs/</PackageProjectUrl>

        <PackageTags>DSL;language;logic;logic-path;system;host;rsml;rsea;decision;oss</PackageTags>
        <PackageReadmeFile>README.md</PackageReadmeFile>
        <PackageIcon>icon.png</PackageIcon>

        <RepositoryType>git</RepositoryType>
        <PackageRequireLicenseAcceptance>true</PackageRequireLicenseAcceptance>
        <NeutralLanguage>en</NeutralLanguage>

        <IsPackable>true</IsPackable>
    </PropertyGroup>
</Project>