<Project Sdk="Microsoft.NET.Sdk.WebAssembly">
	<PropertyGroup>
		<RootNamespace>OceanApocalypse.Wave.IDE.UI.Browser</RootNamespace>
		<TargetFramework>net10.0-browser</TargetFramework>
		<OutputType>Exe</OutputType>
		<AllowUnsafeBlocks>true</AllowUnsafeBlocks>
		<Nullable>enable</Nullable>
	</PropertyGroup>

	<ItemGroup>
		<PackageReference Include="Avalonia.Browser" />
	</ItemGroup>

	<ItemGroup>
		<ProjectReference Include="..\waveIDE.UI\waveIDE.UI.csproj" />
	</ItemGroup>
</Project>
