<Project Sdk="Microsoft.NET.Sdk">

	<PropertyGroup>
		<TargetFramework>net10.0</TargetFramework>
		<RootNamespace>OceanApocalypse.Wave.SDK.Plugins.Runtime</RootNamespace>
		<Nullable>enable</Nullable>
	</PropertyGroup>

	<ItemGroup>
		<PackageReference Include="StreamJsonRpc" />
	</ItemGroup>

	<ItemGroup>
		<ProjectReference
			Include="../../ext/waveEXT.Protocol.Transport/waveEXT.Protocol.Transport.csproj" />
		<ProjectReference
			Include="../../ext/waveEXT.Protocol.AotCompatibility/waveEXT.Protocol.AotCompatibility.csproj" />
	</ItemGroup>

</Project>