<Project Sdk="Microsoft.NET.Sdk">
	<PropertyGroup>
		<RootNamespace>OceanApocalypse.Wave.IDE.UI.Desktop</RootNamespace>

		<OutputType>WinExe</OutputType>
		<!--If you are willing to use platform-specific APIs, use conditional compilation.
		See https://docs.avaloniaui.net/docs/guides/platforms/platform-specific-code/dotnet for more details.-->
		<TargetFramework>net10.0</TargetFramework>
		<Nullable>enable</Nullable>
		<GenerateDocumentationFile>false</GenerateDocumentationFile>
	</PropertyGroup>

	<PropertyGroup Label="Native AOT Setup">
		<PublishAot>true</PublishAot>
		<IsAotCompatible>true</IsAotCompatible>
	</PropertyGroup>

	<PropertyGroup>
		<ApplicationManifest>app.manifest</ApplicationManifest>
	</PropertyGroup>

	<ItemGroup>
		<PackageReference Include="Avalonia.Desktop" />
	</ItemGroup>

	<ItemGroup>
		<ProjectReference Include="..\..\launcher\waveIDE.Launcher.csproj" />
	</ItemGroup>
</Project>
