
####################################################################################### 
## This manifest is a sample and contains all possible fields as of waveSDK in 2026. ##
#######################################################################################


[plugin]	# The main metadata
id = "dev.bob.my-plugin"									# string, mandatory (must follow reverse-domain)
version = "3.0.1"											# string, mandatory (must follow semver)
display_name = "Bob's Awesome Plugin"						# string, optional (defaults to plugin.id)
author = "Bob"												# string, optional (defaults to the domain part of the id - in this case, bob.dev)
license = "Apache-2.0"										# string, optional but highly recommended (SPDX license expression)
url = "https://example.com/bob/plugin"						# string, optional but highly recommended (url)
language = "C#"												# string, optional
conflicts = [ "dev.joe.i-hate-bob", "com.jim.bad-plugin" ]	# string array, optional (defaults to [])


[permissions]	# Permission definitions
# scopes vary with the editor - check the documentation of each editor's plugin manifest
# some editors might also allow wildcards such as workspace:* or even syntax such as workspace:read+write if both are needed
# some editors also infer necessary permissions (if the manifest includes a language or theme, the editor might infer the needed permissions for those)
scopes = [
	"trust:read",
	"workspace:read",
	"workspace:write",
	"debug:write",
	# ...
]
dynamic = true	# boolean, optional (defaults to false)


[entry-point]	# Properties regarding how the plugin runs
kind = "executable"								# string, optional (defaults to executable; options are 'none' and 'executable')
executable = "relative/path/to/the/binary"		# string, mandatory if kind is executable, ignored if not
# ^ decision.json files aren't passed to the editor, they're evaluated and the result will be the 'executable' property instead


[editors]	# Defines the compatibility contract - if the section is fully omitted, it's assumed the plugin wasn't tested in a single editor
# it's the editor that enforces this policy - all waveSDK does is interpret and pass the editor a much cleaner object
compatible = [
	# Syntax reference:
	"a:b",		# is translated to "tag b of editor a" - it's the editor that decides if tag b is absolute nonsense or not
	"a:*",		# if b is a wildcard, it's the same as not adding it (a:* = a = "any tag of editor a")
	"a:b-c",	# is translated to "between tag b and c of editor a" - once again, the SDK doesn't check if the range is fine, it only retrieves it
	"a:b-/",	# is translated to "up to tag b (included) of editor a" - once again, the SDK doesn't check
	# the fact the SDK doesn't check is why you can do things like "editor:pineapple-plum" or "editor:2026-/"
	# btw duplicates will not throw errors because you might want to specify explicitly one version
	# despite it also being included in a range
	# concrete examples below:

	# Targetting entire editors
	"waveIDE", "coolEditor", "otherEditor",
	"waveIDE:*", # same as 'waveIDE'

	# Targetting specific major versions
	"waveIDE:3", "waveIDE:1",

	# Targetting major version ranges
	"waveIDE:3-1",

	# Targetting specific versions (minor or patch)
	"waveIDE:3.0", "waveIDE:3.0.1", "waveIDE:3.0.1-1.1",

	# Targetting every version until a given one (included)
	"waveIDE:2-/", "waveIDE:3.0.1-/", # every version until 3.0.1

	# Non-semver labels
	"waveIDE:2026", "myCoolEditor:2026-2022", "waveIDE:latest", "myOtherEditor:pineapple"
]
incompatible = [ # strictly incompatible editors - follows the same syntax as 'compatible' property
	# if anything is here and also in 'compatible', this property takes priority
	# so if you want to add a big range but avoid one specific version, it's very easy:
	# compatible = [ "editor:a-c" ]
	# incompatible = [ "editor:b" ]
	"waveIDE:beta", "unsafeEditor"
]
unspecified_are_incompatible = true
# ^ bool, defaults to false (if set to true, any editor not in 'compatible' is automatically incompatible)
# if set to false, editors not in 'compatible' are considered compatible, but untested
# it's up to the editor to decide whether something untested should try to run or straight up be disabled


# THEMES
[themes.example-theme]
name = "Example Theme"
file = "path/to/theme"
# ^ each editor has different filetypes

[themes."My Awesome Theme"] # it's possible to use names like these but it's best to save those for the display only
name = "My Awesome Theme"
# no file means the theme is loaded in code - some editors do not allow this

[themes.dev-bob-amazing-theme] # it's recommended to include the domain in the theme section name
name = "Bob's Amazing Theme"
file = "bob-theme.decision.json"
# ^ decision.json files aren't passed to the editor, they're evaluated and the result will be the 'file' property instead


# LOCALIZATION
[[locale]]
iso_name = "pt"			# must match a ISO 639-1/639-3 name
name = "pt-PT"			# must match a .NET culture name
file = "path/to/file"	# path to the file (may be a .decision.json file)

[[locale]]
iso_name = "sk"			# must match a ISO 639-1/639-3 name
name = "sk-SK"			# must match a .NET culture name
file = "path/to/file"	# path to the file (may be a .decision.json file)


# LANGUAGES
[languages.rsml]
id = "rsml"
name = "Red Sea Modern Language"
file_extensions = [ "rsea", "rsml", "decision" ]
mime_type = "application/rsml"

[languages.rsml.capabilities] # some editors read these and add the missing permissions in the scopes
lsp = true
formatter = true
debugger = true
